global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "ai-artistic-style"
    static_configs:
      - targets: ["ai-artistic-style:5001"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
